name: kana-voice-tool
title: Kana Voice Tool
version: 1.0.0
icon: ./assets/icon.png
summary: Kanaの音声合成ツール
description: Kanaの音声合成ツール
base: core20
confinement: classic
grade: stable

apps:
  kana-voice-tool:
    command: kana-voice-tool/kana-voice-tool --no-sandbox
    extensions: [gnome-3-34]
    plugs:
      - alsa
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - opengl
      - pulseaudio
      - unity7
      - wayland
      - x11
    environment:
      DISABLE_WAYLAND: "1"
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  app:
    plugin: nil
    source: .
    override-build: |
      cp -rv . $SNAPCRAFT_PART_INSTALL/kana-voice-tool
    stage-packages: []